name: action
run-name: ${{ github.actor }} asking for main action
on:
  push:
    branches-ignore:
      - "ga-ignore-*"
  pull_request:
    branches-ignore:
      - "ga-ignore-*"

jobs:
  check_program_compilation:
    name: check_program_compilation
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout GH repository
        uses: actions/checkout@v4
        with:
          repository: ""

      - name: Install SDL2
        run: |
              #install sdl2
              sudo apt install libsdl2-dev libsdl2-2.0-0 -y;
              #install sdl image  - if you want to display images
              sudo apt install libjpeg-dev libwebp-dev libtiff5-dev libsdl2-image-dev libsdl2-image-2.0-0 -y;
              #install sdl mixer  - if you want sound
              sudo apt install libmikmod-dev libfishsound1-dev libsmpeg-dev liboggz2-dev libflac-dev libfluidsynth-dev libsdl2-mixer-dev libsdl2-mixer-2.0-0 -y;
              #install sdl true type fonts - if you want to use text
              sudo apt install libfreetype6-dev libsdl2-ttf-dev libsdl2-ttf-2.0-0 -y;

      - name: Compile project
        run: cmake -S . -B build

      - name: Build project
        run: cmake --build build -- -j $(nproc --all)

      # - name: Clean project
      #   run: make clean

      - name: Check executables
        run: |
          for file in ${{ vars.EXECUTABLES }}; do
            if [ ! -x "./build/${file}" ]; then
                echo "File $file does not exist or is not executable"
                exit 1
            fi
          done

  push_to_mirror:
    name: push_to_mirror
    runs-on: ubuntu-latest
    needs: [check_program_compilation]
    if: github.event_name == 'push'
    steps:
      - name: Checkout GH repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to mirror repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ vars.MIRROR_URL }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
